name: flutter_appspector_example
description: A sample app which demonstrates AppSpector initialization and features.
publish_to: none

environment:
  sdk: ">=2.5.0-dev.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  appspector:
    path: ../
  http: ^0.12.0+2
  sqflite: ^1.1.6
  logging: ^0.11.3+2
  dio: ^3.0.4
  fluttertoast: ^3.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/
