name: flutter_appspector_example
description: A sample app which demonstrates AppSpector initialization and features.
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  appspector:
    path: ../
  http: ^0.13.1
  sqflite: ^2.0.0+3
  logging: ^1.0.1
  dio: ^4.0.0
  fluttertoast: ^8.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
