name: appspector
description: A plugin that integrate AppSpector to your Flutter project.
version: 0.0.6
author: AppSpector <info@appspector.com>
homepage: https://github.com/appspector/flutter-plugin

environment:
  sdk: ">=2.3.1-dev.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.appspector.flutter
    pluginClass: AppSpectorPlugin
