name: appspector
description: A plugin that integrate AppSpector to your Flutter project.
version: 0.6.1
homepage: https://github.com/appspector/flutter-plugin

environment:
  sdk: ">=2.3.1 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.appspector.flutter
        pluginClass: AppSpectorPlugin
      ios:
        pluginClass: AppSpectorPlugin
